apiVersion: v1
kind: Service
metadata:
  namespace: kong-system
  name: validating-webhook
  labels:
    control-plane: controller-manager
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
