apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  labels:
    name: gateway-operator-webhook
  name: gateway-operator-admission
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - create
