run:
  timeout: 5m
  skip-dirs:
  - pkg/clientset
  - config/
  - third_party/
  build-tags:
  - integration_tests
  - e2e_tests
linters:
  enable:
  - asciicheck
  - bodyclose
  - dogsled
  - durationcheck
  - errcheck
  - errorlint
  - exhaustive
  - exportloopref
  - gci
  - gofmt
  - goimports
  - gomodguard
  - gosec
  - gosimple
  - govet
  - importas
  - ineffassign
  - megacheck
  - misspell
  - nilerr
  - nolintlint
  - predeclared
  - revive
  - staticcheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - wastedassign
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/kong/gateway-operator)
  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/api/apps/v1
        alias: appsv1
      - pkg: k8s.io/api/admission/v1
        alias: admissionv1
      - pkg: k8s.io/api/certificates/v1
        alias: certificatesv1

      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
      - pkg: sigs.k8s.io/gateway-api/apis/(v[\w\d]+)
        alias: gateway${1}

      - pkg: github.com/kong/gateway-operator/internal/types
        alias: gwtypes
  revive:
    rules:
      - name: context-as-argument
        # TODO: re-add this rule after https://github.com/golangci/golangci-lint/issues/3280
        # is resolved and released.
        # arguments:
        #   - "allowTypesBefore": "*testing.T"
        disabled: true
  exhaustive:
    default-signifies-exhaustive: true
  gomodguard:
    blocked:
      modules:
      - github.com/pkg/errors:
          recommendations:
          - fmt
          - errors
issues:
  max-same-issues: 0
  fix: true
