apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        - name: RELATED_IMAGE_KONG
          value: registry.connect.redhat.com/kong/kong:2.8.1
        - name: RELATED_IMAGE_KONG_CONTROLLER
          value: registry.connect.redhat.com/kong/kong-ingress-controller:2.5.0-redhat
