apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: kong-gateway-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: ControlPlane is the Schema for the controlplanes API
      displayName: Control Plane
      kind: ControlPlane
      name: controlplanes.gateway-operator.konghq.com
      version: v1alpha1
    - description: DataPlane is the Schema for the dataplanes API
      displayName: Data Plane
      kind: DataPlane
      name: dataplanes.gateway-operator.konghq.com
      version: v1alpha1
    - description: GatewayConfiguration is the Schema for the gatewayconfigurations
        API
      displayName: Gateway Configuration
      kind: GatewayConfiguration
      name: gatewayconfigurations.gateway-operator.konghq.com
      version: v1alpha1
  description: Kong Operator for Kubernetes
  displayName: Kong
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - networking
  - gateway
  - ingress
  - kong
  - kubernetes
  - go
  links:
  - name: Operator
    url: https://operator.domain
  maturity: alpha
  provider:
    name: Kong Inc.
    url: https://konghq.com
  version: 0.0.0
