apiVersion: gateway-operator.konghq.com/v1alpha1
kind: ControlPlane
metadata:
  name: controlplane-example
spec:
  dataplane: dataplane-example
  gatewayClass: kong
  deployment:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "1000m"
