apiVersion: gateway-operator.konghq.com/v1alpha1
kind: DataPlane
metadata:
  name: dataplane-example
spec:
  deployment:
    env:
    - name: KONG_LOG_LEVEL
      value: debug
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "1000m"
