name: Build container image(s)

on:
  push:
    branches:
    - 'main'

jobs:
  build-and-push-image:
    uses: ./.github/workflows/build-workflow.yaml
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}

      push: true
      file: Dockerfile
      platforms: linux/amd64, linux/arm64
