name: Test container image(s)

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    uses: ./.github/workflows/build-workflow.yaml
    with:
      registry: ghcr.io
      image-name: ${{ github.repository }}

      push: false
      file: Dockerfile
      # TODO: Figure out the best way to include linux/arm64 by (probably?) using a matrix.
      # Related issue: https://github.com/Kong/gateway-operator/issues/284
      platforms: linux/amd64
      outputs: type=docker,dest=/tmp/image.tar
      upload-artifact: /tmp/image.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp

      - name: Run operator -version
        id: version
        run: |
          docker load --input ${{ needs.build.outputs.artifact }}
          VERSION_JSON=$(docker run ghcr.io/${{ github.repository }}:${{ needs.build.outputs.version }} -version)
          echo "::set-output name=json::${VERSION_JSON}"

      - name: Test operator version
        run: |
          echo '${{ steps.version.outputs.json }}' | ./scripts/verify-version.sh ${{ github.repository }}
